#!/bin/sh

cd "`dirname "$0"`/.."

# Colors
RED=`tput setaf 1`
GREEN=`tput setaf 2`
RESET=`tput sgr0`

cargo fmt -- --write-mode diff \
    || { echo "\n${RED}ERROR${RESET}: Must run \`cargo fmt\` before submitting."; exit 1; }

env RUST_TEST_THREADS=1 cargo test || exit 1

perl -0777 -pe 's/.*## Usage\n\n```rust\n(.*)```.*/$1/s' README.md \
    | colordiff tests/usage.rs - \
    || { echo "\n${RED}ERROR${RESET}: Usage in README.md differs from tests/usage.rs."; exit 1; }

echo "Presubmits ${GREEN}PASSED${RESET}.\n"
