#!/bin/sh

cd "`dirname "$0"`/.."

# Colors
RED=`tput setaf 1`
GREEN=`tput setaf 2`
RESET=`tput sgr0`

cargo fmt -- --write-mode diff \
    || { echo "\n${RED}ERROR${RESET}: Must run \`cargo fmt\` before submitting."; exit 1; }

env RUST_TEST_THREADS=1 cargo test || exit 1

echo "Presubmits ${GREEN}PASSED${RESET}.\n"
